#ifndef POKEPLATINUM_CONSTANTS_MAP_OBJECT_MOVE_H
#define POKEPLATINUM_CONSTANTS_MAP_OBJECT_MOVE_H

#include <nitro/fx/fx_const.h>

#define MAP_OBJECT_MOVE_TILE_SIZE (16 * FX32_ONE)

#endif // POKEPLATINUM_CONSTANTS_MAP_OBJECT_MOVE_H
